### ISSUE TITLE
How to make Kendall/Cosine method faster in clustifyr?

### ISSUE THREAD

**Issue by smk5g5** [rnabioco/clustifyr#349]
Is there a way to make the cosine and kendall method faster in clustifyr. I am trying to use them but they are taking forever.

```
seurat_AML <- clustify(
  input = seurat_AML,
  ref_mat = sce_ref,
  cluster_col = "ClusterNames_0.7_50PC",
  seurat_out = TRUE,
  rename_prefix='Clustify_results_kendall',
  per_cell = TRUE,
  compute_method='kendall'
)
```

**Comment by kriemo** [comment]
Hi there. How many cells are in your seurat object? Using `per_cell = TRUE` can be prohibitively slow with `kendall` or `cosine` as these methods are not optimized for large matrices. We generally do not use recommend using clustifyr per cell because the expression profiles per cell are very noisy. A possible workaround to improve performance is to intentionally overcluster your data to produce clusters with a few cells (e.g. ~10 cells), then use these clusters for running `clustifyr`.  This would reduce the runtime and likely provide more accurate correlation values. 

If you need per cell correlation you could also consider using `doParallel` to run the correlation in parallel to speed up runtime.

e.g.
``` r
library(Seurat)
library(doParallel)
library(clustifyr)

cells <- colnames(pbmc_small)

n_cores <- 4
cell_splits <- split(cells, cut(seq_along(cells), n_cores, labels = FALSE))

cl <- makeCluster(n_cores)  
registerDoParallel(cl)

res <- foreach(i = cell_splits,
        .packages = c("clustifyr", "Seurat"),
        .combine = rbind
) %dopar% {
  clustify(pbmc_small@assays$RNA@counts[, i], 
           ref_mat = cbmc_ref,
           metadata = pbmc_small$RNA_snn_res.0.8[i],
           per_cell = TRUE, 
           compute_method = "kendall"
  )
}

stopCluster(cl)

res[1:5, 1:5]
#>                        B CD14+ Mono CD16+ Mono     CD34+     CD4 T
#> ATGCCAGAACGACT 0.2123524 0.13437511 0.15410387 0.2396228 0.3894390
#> CATGGCCTGTGCAT 0.1650281 0.07159517 0.05646056 0.1301711 0.3672203
#> GAACCTGATGAACC 0.2371433 0.18006251 0.19577406 0.2424738 0.4551803
#> TGACTGGATTCTCA 0.2633766 0.14775280 0.17874755 0.2701568 0.4318928
#> AGTCAGACTGCACA 0.2361978 0.16345664 0.17360170 0.2300744 0.4267764

cor_to_call(res)
#> # A tibble: 80 x 3
#> # Groups:   cluster [80]
#>    cluster        type      r
#>    <chr>          <chr> <dbl>
#>  1 AGGTCATGAGTGTC B     0.386
#>  2 AGAGATGATCTCGC B     0.435
#>  3 GGGTAACTCTAGTG B     0.396
#>  4 CATGAGACACGGGA B     0.385
#>  5 TACGCCACTCCGAA B     0.402
#>  6 CTAAACCTGTGCAT B     0.431
#>  7 GTAAGCACTCATTC B     0.410
#>  8 TTGGTACTGAATCC B     0.422
#>  9 CATCATACGGAGCA B     0.365
#> 10 TACATCACGCTAAC B     0.454
#> # … with 70 more rows
```

<sup>Created on 2020-05-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


We have also considered moving the kendall and cosine methods to c/c++ to improve runtime, but I can't guarantee that these will be implemented anytime soon.

**Comment by smk5g5** [comment]
Thanks!
